### ISSUE TITLE
The card length is not same when the content is too short

### ISSUE THREAD

**Issue by MKFMIKU** [nauzethc/ghost-material#10]
![qq 20160226233947](https://cloud.githubusercontent.com/assets/13622651/13356838/662e4c64-dce2-11e5-9c0e-8e28891635e3.jpg)

As the photo showed, when the content is too short,the card length will be not same as others.
I find the issue [#6](https://github.com/nauzethc/ghost-material/issues/6)
And that is my url: http://blog.kffuck.com/page/3/

**Comment by nauzethc** [comment]
I think now is fixed. `width` on `card` elements was not set.
