### ISSUE TITLE
CSS Markdown

### ISSUE THREAD

**Issue by LM1LC3N7** [nauzethc/ghost-material#12]
Hello,

comments in a `sh` code are not colorized. Is that normal ?

``` sh
$ <command> # comments
```

**Comment by nauzethc** [comment]
The theme doesn't have any syntax coloring theme, you have to use another library for that purpose. I'm using [Highlight.js](https://highlightjs.org/) in my blog.

**Comment by flexbrane** [comment]
Thanks for this information.

But when I load mt ghost site with developer tools (chrome) I can't see any file highlight.js. Is it normal ?
