### ISSUE TITLE
highlight js is not in this repo

### ISSUE THREAD

**Issue by LM1LC3N7** [nauzethc/ghost-material#15]
Hello (again)

I have been verified and there is this line on your blog :

``` html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
```

and in files that I have been downloaded here, there is not this line.

How can I do to add it, and have the same color that your blog ? 

I tried to add

``` html
    {{! Scripts }}
    <script src="{{asset "assets/js/main.js"}}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
```

But it seems do not working. Any solutions ? :)

**Comment by nauzethc** [comment]
You have the instructions on the Highlight.js webpage, I put you the link on your previous issue. Please don't open issues which have nothing to do with this repository.

PD: You also have to include the Highlight.hs CSS.
