### ISSUE TITLE
Question: Why are you not convinced on MDL or Materialize?

### ISSUE THREAD

**Issue by leolorenzoluis** [nauzethc/ghost-material#20]
As title says, could you elaborate why you are not convinced of just using MDL/Materialize?

**Comment by nauzethc** [comment]
Both frameworks are good options to implement Material Design in a web page, but they are too heavy and complex for just a blogging platform.

I wrote the theme to implement just the things I needed from both frameworks and to gain some performance using CSS animations instead Javascript.
