### ISSUE TITLE
El texto de los code tag sale del card

### ISSUE THREAD

**Issue by paulomcnally** [nauzethc/ghost-material#21]
El texto de los code tag sale del card. Cuando se carga la página el texto del tag code se ve bien por que se agrega scroll horizontal, pero en la lista de post el texto largo se sale de los cards.

Aquí unas capturas de pantalla:

http://m.imgur.com/z5fh7lW,B4YBm0y

**Comment by nauzethc** [comment]
ES: Es el comportamiento normal para que el texto no se deforme, las `code` permiten scroll horizontal por este motivo.

EN: It's the normal behaviour to keep the text indentation, `code` tags enable horizontal scrolling.
