### ISSUE TITLE
Card images are not well rendered on smartphone

### ISSUE THREAD

**Issue by NerosTie** [nauzethc/ghost-material#3]
On a smartphone's screen, card images are not well rendered:

![screenshot_2015-11-29-19-13-56_com android chrome](https://cloud.githubusercontent.com/assets/4572452/11459060/3a9301d0-96ce-11e5-8f53-b9b52f46996a.png)

It's ok on landscape mode.

(plus, look at the top, it's cropped when you hit the bottom of the page)

**Comment by nauzethc** [comment]
Which Chrome version are you using on Android? I tested on my Nexus 5 and the theme was displayed well.

**Comment by NerosTie** [comment]
Chrome 46.0.2490.76 (Android 5.02)

Maybe your screen is wider and this is why you don't see this.

**Comment by NerosTie** [comment]
Tested with Firefox 42.0.1: it's OK.
Tested with Chrome 46 on my tablet: it's OK

On my smartphone, I have an other web-browser which use webkit: same issue.

So, it's specific to webkit with a certain screen size.
