### ISSUE TITLE
No newlines in blockquotes

### ISSUE THREAD

**Issue by NerosTie** [nauzethc/ghost-material#4]
This is a blockquote using the material theme:

![ghost_material_1](https://cloud.githubusercontent.com/assets/4572452/11459169/895f776a-96d0-11e5-9961-05ad40d93d24.png)

And this is the same blockquote using the casper theme:

![ghost_material_2](https://cloud.githubusercontent.com/assets/4572452/11459170/987f8262-96d0-11e5-9e06-e7afbd7c3256.png)

As you can see, all the newlines are missing in the material theme.

**Comment by nauzethc** [comment]
I think the problem is the bottom margin on `<p>` elements inside a `<blockquoute>` element.

**Comment by NerosTie** [comment]
Yes, I confirm.

```
.post--content > blockquote > p {
  margin: 0;
}
```

 should be deleted and `margin: 20px 0;` in `.post--content > blockquote` should be smaller.

**Comment by nauzethc** [comment]
I've fixed adding some `margin-bottom` on all `<p>` but last child.
