### ISSUE TITLE
Card image is messy when there is no cover image

### ISSUE THREAD

**Issue by NerosTie** [nauzethc/ghost-material#5]
When a post has no cover image, the "card image" at the bottom is messy.

![ghost_material_3](https://cloud.githubusercontent.com/assets/4572452/11470579/40cbd996-975f-11e5-8c06-97393945a269.png)

It shouldn't be transparent by default when there is no cover image to avoid this issue.

**Comment by nauzethc** [comment]
I think is fixed now. I've added some background color when no images are displayed. Could you check it with last version? You have to update `screen.css`, `theme.css` and `navcard.hbs`.

**Comment by NerosTie** [comment]
It looks good to me. Thanks! :+1:
