### ISSUE TITLE
The card slide's length should be fixed (not variable)

### ISSUE THREAD

**Issue by NerosTie** [nauzethc/ghost-material#6]
This is an example of the issue:

As you can see, the length of these 2 posts are not the same.
It happens when the title is too short.

**Comment by nauzethc** [comment]
Could you send me the entire HTML code? I need to know the context where these cards are placed to check the CSS rules.

**Comment by NerosTie** [comment]
http://pastebin.com/Y6efU8AC

This?

**Comment by nauzethc** [comment]
Yeah, thanks. I'll check it later.
