### ISSUE TITLE
这个效果很炫

### ISSUE THREAD

**Issue by shangxinbo** [nauzethc/ghost-material#8]
效果真的很喜欢，但如果文章没有主题图片就会显示有些别扭

**Comment by nauzethc** [comment]
English please

**Comment by shangxinbo** [comment]
I like this effect.But if I did not have a picture of the article, it will feel strange,in my option.

**Comment by nauzethc** [comment]
I guess you mean navcards on the bottom part of the post. `div` element with `no-image` class is rendered when post hasn't any image associated. `no-image` class is a black background by default.
